apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: {{ .Values.namespace }}
  labels:
    app: assets
    project: karatu-2025-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
        - name: assets
          image: public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: assets
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: assets
  ports:
    - port: 80
      targetPort: 8080
