apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.catalog.db.host }}
  ports:
    - port: {{ .Values.catalog.db.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.orders.db.host }}
  ports:
    - port: {{ .Values.orders.db.port }}
