apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: retail-app
type: Opaque
stringData:
  username: admin
  password: BedrockMySQL2026!
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: retail-app
type: Opaque
stringData:
  username: dbadmin
  password: BedrockPostgres2026!
